version: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    build:
      context: .
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-sing-box-server
    container_name: ipsec-sing-box-server
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
      - ./sing-box/config.json:/etc/sing-box/config.json:ro
